version: "3.9"

services:
  monolito:
    build: ./monolito
    ports:
      - "5000:5000"
    environment:
      - API_KEY=supersecreta123
    depends_on:
      - redis
    volumes:
      - ./monolito:/app
    restart: always

  redis:
    image: redis:7
    container_name: redis-cache
    ports:
      - "6379:6379"
    restart: always

networks:
  default:
    name: tfu3_network
